# Generated by Django 5.2.4 on 2025-08-11 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('user', models.OneToOneField(help_text='지갑의 소유자', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.PositiveIntegerField(default=0, help_text='현재 보유 캐시 잔액')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='마지막 잔액 변동 시간')),
            ],
        ),
        migrations.CreateModel(
            name='CashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('charge', '충전'), ('use', '사용')], help_text='로그 종류 (충전/사용)', max_length=10)),
                ('amount', models.IntegerField(help_text='변동된 캐시 양 (충전: 양수, 사용: 음수)')),
                ('description', models.CharField(blank=True, help_text='거래에 대한 간단한 설명 (예: AI 상담, 이벤트 보상)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='로그 생성 시간')),
                ('wallet', models.ForeignKey(help_text='관련된 사용자 지갑', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='users.userwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
