# Generated by Django 5.2.5 on 2025-08-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_sanctioned_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2000-01-01', verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], default='M', max_length=1, verbose_name='성별'),
        ),
        migrations.DeleteModel(
            name='CashLog',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
