version: "3.9"

services:
  backend:
    build: ./backend
    restart: always
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - ./backend:/app
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev   # 개발용 Dockerfile (npm start)
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - backend
      - frontend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
