# docker-compose.yml

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py seed_influencers && daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - ./backend:/app
    ports:
      - "0.0.0.0:8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    extra_hosts:
      - "runpod.server:69.30.85.5"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:3000:3000"

    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

volumes:
  pgdata:
  redisdata: