# Generated by Django 5.2.5 on 2025-08-20 04:57

import chat.models
import chat.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_description_chatroom_influencer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='채팅방 썸네일 이미지', null=True, storage=chat.storage.OverwriteStorage(), upload_to=chat.models.chatroom_thumbnail_path),
        ),
    ]
