# Generated by Django 5.2.5 on 2025-08-29 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_streamerttssettings_coqui_model_and_more'),
        ('influencers', '0002_rename_name_real_influencer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='influencer',
            field=models.ForeignKey(blank=True, help_text='채팅방과 연결된 인플루언서', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='influencers.influencer'),
        ),
    ]
