# Generated by Django 5.2.5 on 2025-09-02 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_streamerttssettings_coqui_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='사연 제목', max_length=255)),
                ('body', models.TextField(help_text='사연 본문')),
                ('status', models.CharField(choices=[('pending', '대기'), ('reading', '읽는 중'), ('done', '완료')], default='pending', help_text='사연 처리 상태', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='제출 시간')),
                ('user', models.ForeignKey(help_text='사연을 제출한 사용자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['submitted_at'],
            },
        ),
    ]
