# Generated by Django 5.2.5 on 2025-09-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatroom_influencer'),
        ('chat', '0009_story'),
    ]

    operations = [
    ]
