# Generated by Django 5.2.6 on 2025-09-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatroom_hls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamerttssettings',
            name='elevenlabs_voice_name',
            field=models.CharField(default='안은진', help_text='ElevenLabs 음성 이름 (표시용)', max_length=100),
        ),
    ]
