# Generated by Django 5.2.5 on 2025-08-29 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='name_real',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='name_ko',
        ),
    ]
