# Generated by Django 5.2.6 on 2025-09-10 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_story_nickname_story_relationship_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerTTSSettings',
            fields=[
                ('influencer', models.OneToOneField(help_text='TTS 설정이 적용될 인플루언서', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tts_settings', serialize=False, to='influencers.influencer')),
                ('tts_engine', models.CharField(default='elevenlabs', help_text='사용할 TTS 엔진 (elevenlabs)', max_length=50)),
                ('elevenlabs_voice', models.CharField(default='aneunjin', help_text='ElevenLabs 음성 ID', max_length=100)),
                ('elevenlabs_voice_name', models.CharField(blank=True, default='안은진', help_text='ElevenLabs 음성 이름 (표시용)', max_length=100)),
                ('elevenlabs_model', models.CharField(default='eleven_multilingual_v2', help_text='ElevenLabs 모델', max_length=100)),
                ('elevenlabs_stability', models.FloatField(default=0.5, help_text='ElevenLabs 안정성 (0.0-1.0)')),
                ('elevenlabs_similarity', models.FloatField(default=0.8, help_text='ElevenLabs 유사성 (0.0-1.0)')),
                ('elevenlabs_style', models.FloatField(default=0.0, help_text='ElevenLabs 스타일 (0.0-1.0)')),
                ('elevenlabs_speaker_boost', models.BooleanField(default=True, help_text='ElevenLabs 스피커 부스트')),
                ('auto_play', models.BooleanField(default=True, help_text='AI 메시지 자동 음성 재생')),
                ('streaming_delay', models.IntegerField(default=50, help_text='스트리밍 지연 시간 (ms)')),
                ('tts_delay', models.IntegerField(default=500, help_text='TTS 지연 시간 (ms)')),
                ('chunk_size', models.IntegerField(default=3, help_text='텍스트 청크 크기')),
                ('sync_mode', models.CharField(default='after_complete', help_text='동기화 모드 (real_time, after_complete, chunked)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='마지막 설정 변경자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Influencer TTS Setting',
                'verbose_name_plural': 'Influencer TTS Settings',
                'ordering': ['influencer__name'],
            },
        ),
    ]
