# Generated by Django 5.2.4 on 2025-08-01 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='members',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(help_text='메시지 내용'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='메시지가 보내진 시간'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(help_text='메시지가 속한 채팅방', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(help_text='메시지를 보낸 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='채팅방이 생성된 시간'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(help_text='채팅방의 이름', max_length=255),
        ),
        migrations.CreateModel(
            name='ChatRoomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enter', '입장'), ('exit', '퇴장')], help_text='수행한 행동 (입장/퇴장)', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='행동이 발생한 시간')),
                ('room', models.ForeignKey(help_text='관련 채팅방', on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('user', models.ForeignKey(help_text='기록의 주체 사용자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ChatRoomMember',
        ),
    ]
