# Generated by Django 5.2.4 on 2025-08-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatroom_members_alter_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='채팅방이 종료된 시간', null=True),
        ),
    ]
