# Generated by Django 5.2.5 on 2025-08-14 06:05

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_streamerttssettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True, help_text='방송 설명', null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='influencer',
            field=models.ForeignKey(blank=True, help_text='채팅방과 연결된 인플루언서', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('pending', '준비중'), ('live', '방송중'), ('finished', '방송종료')], default='pending', help_text='방송 상태', max_length=10),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='채팅방 썸네일 이미지', null=True, upload_to=chat.models.chatroom_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='host',
            field=models.ForeignKey(help_text='채팅방을 생성한 호스트(관리자)', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(help_text='방송 제목', max_length=255),
        ),
    ]
