# Generated by Django 5.2.5 on 2025-08-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatroom_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamerttssettings',
            name='coqui_model',
        ),
        migrations.RemoveField(
            model_name='streamerttssettings',
            name='coqui_speaker',
        ),
        migrations.RemoveField(
            model_name='streamerttssettings',
            name='melo_voice',
        ),
        migrations.AlterField(
            model_name='streamerttssettings',
            name='tts_engine',
            field=models.CharField(default='elevenlabs', help_text='사용할 TTS 엔진 (elevenlabs)', max_length=50),
        ),
    ]
