# Generated by Django 5.2.6 on 2025-09-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_merge_0009_alter_chatroom_influencer_0009_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='hls_url',
            field=models.URLField(blank=True, help_text='라이브 스트리밍을 위한 HLS 주소입니다.', max_length=512, null=True, verbose_name='HLS 스트림 URL'),
        ),
    ]
