# Generated by Django 5.2.5 on 2025-08-29 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=50, unique=True, verbose_name='활동명')),
                ('name_real', models.CharField(max_length=50, verbose_name='실제 이름')),
                ('age', models.PositiveIntegerField(verbose_name='나이')),
                ('gender', models.CharField(choices=[('남', '남성'), ('여', '여성')], max_length=10, verbose_name='성별')),
                ('mbti', models.CharField(blank=True, max_length=10, verbose_name='MBTI')),
                ('job', models.TextField(verbose_name='현재 직업')),
                ('social_status', models.TextField(blank=True, verbose_name='사회적 지위')),
                ('audience_term', models.CharField(blank=True, max_length=50, verbose_name='시청자 호칭')),
                ('origin_story', models.TextField(blank=True, verbose_name='기원 스토리')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='프로필 이미지')),
            ],
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=100, unique=True, verbose_name='가치 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationStyle',
            fields=[
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='communication_style', serialize=False, to='influencers.influencer')),
                ('tone', models.TextField(blank=True, verbose_name='어조')),
                ('sentence_length', models.TextField(blank=True, verbose_name='문장 길이')),
                ('question_style', models.TextField(blank=True, verbose_name='질문 습관')),
                ('directness', models.PositiveIntegerField(blank=True, help_text='1~5점 척도', null=True, verbose_name='직설성')),
                ('empathy_expression', models.TextField(blank=True, verbose_name='공감 표현 방식')),
            ],
        ),
        migrations.CreateModel(
            name='MoralCompass',
            fields=[
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='moral_compass', serialize=False, to='influencers.influencer')),
                ('standard', models.TextField(blank=True, verbose_name='기준')),
                ('rule_adherence', models.TextField(blank=True, verbose_name='규칙 준수')),
                ('fairness', models.TextField(blank=True, verbose_name='공정성')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personality_trait', serialize=False, to='influencers.influencer')),
                ('energy_direction', models.TextField(blank=True, verbose_name='에너지 방향')),
                ('emotional_processing', models.TextField(blank=True, verbose_name='감정 처리')),
                ('judgment_decision', models.TextField(blank=True, verbose_name='판단·결정')),
                ('interpersonal_attitude', models.TextField(blank=True, verbose_name='대인 태도')),
                ('openness', models.TextField(blank=True, verbose_name='개방성')),
                ('conscientiousness', models.TextField(blank=True, verbose_name='성실성')),
                ('emotional_stability', models.TextField(blank=True, verbose_name='감정 안정성')),
                ('social_sensitivity', models.TextField(blank=True, verbose_name='사회적 민감성')),
                ('risk_preference', models.TextField(blank=True, verbose_name='위험 선호')),
                ('time_orientation', models.TextField(blank=True, verbose_name='시간 지향성')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerCoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=99, help_text='낮을수록 우선순위가 높음 (Top 3)')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencers.influencer')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencers.corevalue')),
            ],
            options={
                'ordering': ['influencer', 'priority'],
                'unique_together': {('influencer', 'value')},
            },
        ),
        migrations.AddField(
            model_name='influencer',
            name='core_values',
            field=models.ManyToManyField(related_name='influencers', through='influencers.InfluencerCoreValue', to='influencers.corevalue', verbose_name='핵심 가치'),
        ),
    ]
