# Generated by Django 5.2.5 on 2025-09-04 05:01

import django.db.models.deletion
import influencers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_rename_name_real_influencer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='social_status',
        ),
        migrations.AddField(
            model_name='influencer',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=influencers.models.influencer_banner_image_path, verbose_name='배너 이미지'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='체크 해제 시 사용자에게 노출되지 않습니다.', verbose_name='활성 상태'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='name',
            field=models.CharField(help_text='방송에서 사용할 인플루언서의 이름입니다.', max_length=50, unique=True, verbose_name='활동명'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=influencers.models.influencer_profile_image_path, verbose_name='프로필 이미지'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='후원액 (크레딧)')),
                ('donated_at', models.DateTimeField(auto_now_add=True, verbose_name='후원일')),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='후원자')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='influencers.influencer', verbose_name='후원받은 인플루언서')),
            ],
            options={
                'verbose_name': '후원 내역',
                'verbose_name_plural': '후원 내역 목록',
                'ordering': ['-donated_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='익명 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('author', models.ForeignKey(blank=True, help_text='비회원은 null, 탈퇴한 회원의 글은 유지됩니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='influencers.influencer', verbose_name='대상 인플루언서')),
            ],
            options={
                'verbose_name': '사연',
                'verbose_name_plural': '사연 게시판',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='influencers.influencer', verbose_name='인플루언서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요 목록',
                'unique_together': {('influencer', 'user')},
            },
        ),
    ]
