# Generated by Django 5.2.6 on 2025-09-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_remove_influencer_social_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='닉네임'),
        ),
        migrations.AddField(
            model_name='story',
            name='relationship_stage',
            field=models.CharField(blank=True, max_length=50, verbose_name='관계 단계'),
        ),
    ]
