# Generated by Django 5.2.5 on 2025-08-24 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='결제 요청 금액 (크레딧 양)')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='고유 주문 ID', unique=True)),
                ('payment_key', models.CharField(blank=True, help_text='토스페이먼츠 결제 키', max_length=200, null=True)),
                ('status', models.CharField(choices=[('ready', '미결제'), ('paid', '결제완료'), ('cancelled', '결제취소'), ('failed', '결제실패')], db_index=True, default='ready', help_text='결제 상태', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='거래 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='마지막 상태 변경 시간')),
                ('user', models.ForeignKey(help_text='결제를 요청한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
