# Generated by Django 5.2.5 on 2025-08-29 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0002_rename_name_real_influencer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField(verbose_name='요청 텍스트')),
                ('tts_settings_snapshot', models.JSONField(default=dict, verbose_name='TTS 설정 스냅샷')),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('ERROR', '실패'), ('PENDING', '대기중')], default='PENDING', max_length=10, verbose_name='처리 상태')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='에러 메시지')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='처리 시간 (ms)')),
                ('audio_file_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='오디오 파일 경로')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 시간')),
                ('influencer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencers.influencer', verbose_name='대상 인플루언서')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='요청 사용자')),
            ],
            options={
                'verbose_name': 'TTS 디버그 로그',
                'verbose_name_plural': 'TTS 디버그 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
