# Generated by Django 5.2.4 on 2025-08-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userwallet_cashlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sanctioned_until',
            field=models.DateTimeField(blank=True, help_text='이 필드에 미래의 날짜가 설정되면, 해당 날짜까지 사용자는 제재 상태입니다.', null=True),
        ),
    ]
